Algoritmo "Questão 05"
// 5) Fazer um algoritmo que calcule e apresente o
// valor do volume de uma lata de óleo.
Var
// Seção de Declarações das variáveis 
   R,a,v: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Informe o Raio da lata de óleo: ")
   Leia(R)
   
   escreval("Informe a altura da lata de óleo: ")
   Leia(a)
   
   v <- 3.14 * r^2 * a
   
   escreval("O volume da lata de óleo é: ", v)
Fimalgoritmo